### ISSUE TITLE
Bots are jerking around

### ISSUE THREAD

**Issue by kakahost** [ineedbots/piw5_bot_warfare#111] opened 2024-08-12 12:04 UTC
They became extremely dumb. Enemies stand on one place and don't shoot, teammates doing... I dunno what are they doing, shooting walls and throwing grenades in them?

**Comment by ineedbots** [comment] 2024-08-12 13:25
dupe of #109 make sure to remove any old bot warfare files

**Comment by kakahost** [comment] 2024-08-13 03:07
Me and my friend have fresh MW3 install, same as fresh plutonium. We are both having this problem.

**Comment by kakahost** [comment] 2024-08-13 03:07
And I checked for the old files, there's nothing.

**Comment by ineedbots** [comment] 2024-08-13 14:50
make sure you are on the latest version of plutonium and bot warfare

**Comment by ineedbots** [comment] 2024-08-13 17:27
dupe of #100

**Closed as completed** 2024-08-16 22:57 UTC
