### ISSUE TITLE
DLC WAYPOINTS PROGRESS

### ISSUE THREAD

**Issue by Bookcollector1** [ineedbots/piw5_bot_warfare#56] opened 2022-03-18 21:01 UTC
Thank you everyone for your hard work and dedication to bring muchly anticipated Bot support for MW3!
My hope is to start a discussion regarding plans and progress posts for DLC Map Support for contributors.

**Comment by ineedbots** [comment] 2022-03-19 03:26
dupe of #6

**Closed by ineedbots** 2022-03-19 03:26 UTC
