### ISSUE TITLE
2.3.0 Version Bots won't work.

### ISSUE THREAD

**Issue by Kraken56YT** [ineedbots/piw5_bot_warfare#105] opened 2024-06-13 09:59 UTC
Everytime I add 17 bots on MW3 IW5 I get this error "exceeded maximum number of parent script variables" and everytime I shoot a bot the game lags way too much which crashes the game after some time later. Anyone know how to fix this problem? It's been happening to me for a month now. Please let me know if you do know how to fix this. Thanks.

**Comment by ineedbots** [comment] 2024-06-13 16:54
dupe of #104 

Please make sure to clean out older files of botwarfare

**Comment by Kraken56YT** [comment] 2024-06-13 23:00
How do I know which older files need to be cleaned out?

**Comment by Kraken56YT** [comment] 2024-06-14 01:41
Nvm I figured it out. Thanks for helping me out. I owe you one.

**Closed as completed** 2024-06-14 01:41 UTC
