### ISSUE TITLE
Bots just spinning on max difficulty and still have no skill? 

### ISSUE THREAD

**Issue by LegitDelirium** [ineedbots/piw5_bot_warfare#102] opened 2024-05-28 01:15 UTC
Have bots set to difficulty "very hard" and I'm easily dropping doable MOABs in game. most of the bots freeze in place, spin in circles, or just have 0% accuracy. Messed with every setting and tried every difficulty and they walk around for a bit then get stuck and spin in circles occasionally but when working properly they just have no skill. worse than black ops 2 recruit difficulty in terms of player skill level when on maximum difficulty but the main issue is just the spinning in circles and getting stuck constantly

**Comment by marcusbbb12** [comment] 2024-06-01 05:20
I am also having this problem. I'm wondering if somehow it's an issue with plutonium. I had 2.1.0 installed, and never had this issue before today. When I noticed the bots were unintelligent, I updated to the most recent version of Bot Warfare and the issue still persisted. I hope this can be easily fixed.

**Comment by Trippledesigns** [comment] 2024-06-01 09:22
there is also a new issue with mw3 on the dlc 4 since the plutonium update i cant play any of them maps so maybe they messed up more than the bots, i did some testing and for me the best experience was leaving the bots on random for all the default i think but if you turn them up to very hard yeah they become stupid maybe i have helped with this maybe not but thats what works on my end, ive only had the map issues since i formated my pc and reinstalled everything yesterday
________________________________

**Comment by ineedbots** [comment] 2024-06-07 20:17
dupe of #98   please use latest versions of the mod and plutonium

**Closed as completed by ineedbots** 2024-06-07 20:17 UTC
