### ISSUE TITLE
Bots cannot be damaged or damage the player

### ISSUE THREAD

**Issue by vixraine** [ineedbots/piw5_bot_warfare#104] opened 2024-06-03 12:05 UTC
Plutonium IW5 r4047
IW5 MP Build 388110
Bot Warfare v2.3.0

When bots deal or take damage, a script error shows up in the console (see screenshot)
![2024-06-03_15-00-16](https://github.com/ineedbots/iw5_bot_warfare/assets/51852802/12d134cf-9170-4aa5-868f-80e015cb15e0)

**Comment by ineedbots** [comment] 2024-06-07 20:11
dupe of #95 , please make sure to clean out old/other gsc scripts that might be interfering with bot warfare

It appears you have a bots.gsc script inside of your `scripts` folder, the correct location is `scripts/mp`, make sure there is only one bots.gsc

**Closed as completed by ineedbots** 2024-06-07 20:11 UTC
