### ISSUE TITLE
the game sometimes crashes after a round

### ISSUE THREAD

**Issue by Tariqozoo** [ineedbots/piw5_bot_warfare#63] opened 2022-05-08 11:26 UTC
the game crashes after a round

**Comment by ineedbots** [comment] 2022-05-08 21:19
lack of info, possible dupe of #26 

mod unrelated.

**Closed by ineedbots** 2022-05-08 21:19 UTC

**Comment by Tariqozoo** [comment] 2022-05-09 08:27
so you mean that there is no way to fix it?
